kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ci-storage
  labels:
    name: jenkins
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/vsphere-volume
parameters:
  diskformat: zeroedthick
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-volume
  annotations:
    volume.beta.kubernetes.io/storage-class: ci-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ci-storage
